trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install .[dev]
  displayName: 'Install with dev dependencies'

- script: |
    flake8 src
  displayName: 'Style check'

- script: |
    mypy src
  displayName: 'Type check'

# - script: |
#     pytest
#   displayName: 'pytest'
